services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
  
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: deti